tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-tertiary-container": "#ffc5ac",
                    "secondary": "#4b5e84",
                    "outline-variant": "#c2c6d4",
                    "surface": "#f8f9fa",
                    "on-primary-fixed": "#001a40",
                    "outline": "#727784",
                    "surface-bright": "#f8f9fa",
                    "secondary-container": "#bed2fe",
                    "on-surface": "#191c1d",
                    "on-secondary": "#ffffff",
                    "primary-fixed-dim": "#acc7ff",
                    "inverse-surface": "#2e3132",
                    "primary": "#00408b",
                    "on-background": "#191c1d",
                    "on-secondary-container": "#475a7f",
                    "surface-tint": "#0e5bbb",
                    "on-secondary-fixed": "#031b3d",
                    "error-container": "#ffdad6",
                    "surface-dim": "#d9dadb",
                    "on-error": "#ffffff",
                    "on-primary-container": "#bed2ff",
                    "tertiary-fixed-dim": "#ffb595",
                    "background": "#f8f9fa",
                    "on-tertiary": "#ffffff",
                    "primary-container": "#0057b7",
                    "tertiary": "#752b00",
                    "tertiary-container": "#9b3c01",
                    "on-primary-fixed-variant": "#004492",
                    "on-secondary-fixed-variant": "#34476b",
                    "on-tertiary-fixed-variant": "#7c2e00",
                    "secondary-fixed": "#d7e2ff",
                    "surface-container-highest": "#e1e3e4",
                    "surface-variant": "#e1e3e4",
                    "on-surface-variant": "#424752",
                    "surface-container": "#edeeef",
                    "surface-container-low": "#f3f4f5",
                    "tertiary-fixed": "#ffdbcd",
                    "surface-container-high": "#e7e8e9",
                    "surface-container-lowest": "#ffffff",
                    "primary-fixed": "#d7e2ff",
                    "secondary-fixed-dim": "#b3c7f2",
                    "inverse-primary": "#acc7ff",
                    "on-error-container": "#93000a",
                    "inverse-on-surface": "#f0f1f2",
                    "on-tertiary-fixed": "#360f00",
                    "on-primary": "#ffffff",
                    "error": "#ba1a1a"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "fontFamily": {
                    "headline": ["Public Sans"],
                    "body": ["Public Sans"],
                    "label": ["Inter"]
            }
          },
        },
}
